python performance_rec_full.py -c 24 -s 128
python performance_rec_full.py -c 23 -s 128
python performance_rec_full.py -c 22 -s 128
python performance_rec_full.py -c 21 -s 128
python performance_rec_full.py -c 20 -s 128
python performance_rec_full.py -c 19 -s 128
python performance_rec_full.py -c 18 -s 128
python performance_rec_full.py -c 17 -s 128
python performance_rec_full.py -c 16 -s 128
python performance_rec_full.py -c 15 -s 128
python performance_rec_full.py -c 14 -s 128
python performance_rec_full.py -c 13 -s 128
python performance_rec_full.py -c 12 -s 128
python performance_rec_full.py -c 11 -s 128
python performance_rec_full.py -c 10 -s 128
python performance_rec_full.py -c 9 -s 128
python performance_rec_full.py -c 8 -s 128
python performance_rec_full.py -c 7 -s 128
python performance_rec_full.py -c 6 -s 128
python performance_rec_full.py -c 5 -s 128
python performance_rec_full.py -c 4 -s 128
python performance_rec_full.py -c 3 -s 128
python performance_rec_full.py -c 2 -s 128
python performance_rec_full.py -c 1 -s 128
python performance_rec_full.py -c 24 -s 64
python performance_rec_full.py -c 23 -s 64
python performance_rec_full.py -c 22 -s 64
python performance_rec_full.py -c 21 -s 64
python performance_rec_full.py -c 20 -s 64
python performance_rec_full.py -c 19 -s 64
python performance_rec_full.py -c 18 -s 64
python performance_rec_full.py -c 17 -s 64
python performance_rec_full.py -c 16 -s 64
python performance_rec_full.py -c 15 -s 64
python performance_rec_full.py -c 14 -s 64
python performance_rec_full.py -c 13 -s 64
python performance_rec_full.py -c 12 -s 64
python performance_rec_full.py -c 11 -s 64
python performance_rec_full.py -c 10 -s 64
python performance_rec_full.py -c 9 -s 64
python performance_rec_full.py -c 8 -s 64
python performance_rec_full.py -c 7 -s 64
python performance_rec_full.py -c 6 -s 64
python performance_rec_full.py -c 5 -s 64
python performance_rec_full.py -c 4 -s 64
python performance_rec_full.py -c 3 -s 64
python performance_rec_full.py -c 2 -s 64
python performance_rec_full.py -c 1 -s 64
python performance_rec_full.py -c 24 -s 32
python performance_rec_full.py -c 23 -s 32
python performance_rec_full.py -c 22 -s 32
python performance_rec_full.py -c 21 -s 32
python performance_rec_full.py -c 20 -s 32
python performance_rec_full.py -c 19 -s 32
python performance_rec_full.py -c 18 -s 32
python performance_rec_full.py -c 17 -s 32
python performance_rec_full.py -c 16 -s 32
python performance_rec_full.py -c 15 -s 32
python performance_rec_full.py -c 14 -s 32
python performance_rec_full.py -c 13 -s 32
python performance_rec_full.py -c 12 -s 32
python performance_rec_full.py -c 11 -s 32
python performance_rec_full.py -c 10 -s 32
python performance_rec_full.py -c 9 -s 32
python performance_rec_full.py -c 8 -s 32
python performance_rec_full.py -c 7 -s 32
python performance_rec_full.py -c 6 -s 32
python performance_rec_full.py -c 5 -s 32
python performance_rec_full.py -c 4 -s 32
python performance_rec_full.py -c 3 -s 32
python performance_rec_full.py -c 2 -s 32
python performance_rec_full.py -c 1 -s 32
python performance_rec_full.py -c 24 -s 16
python performance_rec_full.py -c 23 -s 16
python performance_rec_full.py -c 22 -s 16
python performance_rec_full.py -c 21 -s 16
python performance_rec_full.py -c 20 -s 16
python performance_rec_full.py -c 19 -s 16
python performance_rec_full.py -c 18 -s 16
python performance_rec_full.py -c 17 -s 16
python performance_rec_full.py -c 16 -s 16
python performance_rec_full.py -c 15 -s 16
python performance_rec_full.py -c 14 -s 16
python performance_rec_full.py -c 13 -s 16
python performance_rec_full.py -c 12 -s 16
python performance_rec_full.py -c 11 -s 16
python performance_rec_full.py -c 10 -s 16
python performance_rec_full.py -c 9 -s 16
python performance_rec_full.py -c 8 -s 16
python performance_rec_full.py -c 7 -s 16
python performance_rec_full.py -c 6 -s 16
python performance_rec_full.py -c 5 -s 16
python performance_rec_full.py -c 4 -s 16
python performance_rec_full.py -c 3 -s 16
python performance_rec_full.py -c 2 -s 16
python performance_rec_full.py -c 1 -s 16

